---
title: "ST558 Project 2"
author: "Zack Vaskalis"
date: "07/03/2020"
output: 
  rmarkdown::github_document:
    toc: TRUE
    toc_depth: 4
    html_preview: TRUE
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## Project Objectives 

The main two objectives for this project are to create predictive models and automate R Markdown documents.

## Data 

This project uses, for analysis, the Online News Popularity Data Set which can be found at the University of California Irvine [UCI Machine Learning Repository, Center for Machine Learning and Intelligent Systems](https://archive.ics.uci.edu/ml/datasets/Online+News+Popularity#). The dataset being used here was compiled by several researchers in Portugal, who collected articles from [Mashable](www.mashable.com) and compiled associated statistics for a period of two years, with the goal of being able to predict the number of shares in social networks (a measure of popularity). The dataset has over 39,000 records of information spanning the two year time period from January 07, 2013 to December 27th, 2014.  The dataset also contains 61 variables, of which 58 are predictive attributes, 2 non-predictive variables(the source url and the time between article publication and dataset acquisition), and finally the goal field for prediction: the number of shares.

### Information on Variables for Analysis:

Out of the 61 Attributes available in this dataset for analysis, in order not to overfit the model with too many dependent variables (which could yield not enough generalization of the dataset to make predictions, especially valid ones), I have chosen to use the following 14 predictor variables and of course the 1 outcome variable we are trying to predict, `shares`.  The weekday variables are also included, but only for subsetting the data by the day of the week.  Once we have the "Monday" dataset, for instance, all of these `weekday_is_*` variables will be removed from the dataset.  The variables selected are below, and the reasoning behind their selection follows.

Attribute Information:    
1.  `n_tokens_content`: Number of words in the content    
2.  `num_hrefs`: Number of links    
3.  `average_token_length`: Average length of the words in the content    
4.  `kw_avg_min`: Worst keyword (avg. shares)    
5.  `kw_avg_max`: Best keyword (avg. shares)    
6.  `kw_min_avg`: Avg. keyword (min. shares)    
7.  `kw_max_avg`: Avg. keyword (max. shares)    
8.  `kw_avg_avg`: Avg. keyword (avg. shares)    
9.  `LDA_00`: Closeness to LDA topic 0    
10.  `LDA_04`: Closeness to LDA topic 4    
11.  `global_subjectivity`: Text subjectivity    
12.  `global_sentiment_polarity`: Text sentiment polarity    
13.  `title_subjectivity`: Title subjectivity    
14.  `abs_title_subjectivity`: Absolute subjectivity level    
15.  `shares`: Number of shares (target outcome trying to predict)    
16.  `weekday_is_variables`: Was the article published on a _______?    

  *  `weekday_is_monday`: Was the article published on a Monday?    
  *  `weekday_is_tuesday`: Was the article published on a Tuesday?    
  *  `weekday_is_wednesday`: Was the article published on a Wednesday?    
  *  `weekday_is_thursday`: Was the article published on a Thursday?    
  *  `weekday_is_friday`: Was the article published on a Friday?    
  *  `weekday_is_saturday`: Was the article published on a Saturday?    
  *  `weekday_is_sunday`: Was the article published on a Sunday?    

For this dataset of nearly 60 predictor variables, a dataset for analysis that contains approximately 25% of them seems to feel right, since too many predictor variables can cause overfitting.  This subset of variables is a sampling across the set of variables I thought might have an impact.  For example, the number of words of content (`n_tokens_content`), and the number of links (`num_hrefs`) seemed reasonable that they might play a role in predicting shares.  The `kw_` variables also seem like they should be good predictors.  I chose the first and last `LDA` variables.  The global ratings also seemed like they would have an impact on predicting the shares so I chose `global_subjectivity` and `global_sentiment_polarity`.  Then finally, to round out the dataset of predictors I chose the title subjectivity and absolutely subjectivity level, since often a title will have the largest impact - catchy or provoking titles are clickbait for a reason!

### Purpose of the Analysis

The ultimate purpose of this analysis is to create 2 models (one linear and one non-linear) for predicting the shares variable, which is in some sense is a measure of popularity.  In addition to this purpose, another primary purpose is to explore using parameter functionality within R Markdown to automatically generate analysis reports for each day of the week, using each `weekday_is_` variable as a parameter.

### Methods for Analysis

As mentioned above, there will be 2 models created within this project, one linear and one non-linear.  

#### Multiple-Linear Regression (MLR) Model

The linear model we will use for our 14 predictor variables will be a multiple linear regression model, without interactions or quadratic terms.  This is in part why the datasets being used for training and testing only contain the variables we need for analysis - which will simplify the code as we will see below.  This model also allows us to use the root mean squared error (RMSE), which is an important topic in statistics in general.  Karen Grace-Martin has a nice description of RMSE in a succinct blog post titled: [Assessing the Fit of Regression Models](https://www.theanalysisfactor.com/assessing-the-fit-of-regression-models/#:~:text=The%20RMSE%20is%20the%20square,an%20absolute%20measure%20of%20fit).  The RMSE is the square root of the variance of the residuals. It indicates the absolute fit of the model to the data–how close the observed data points are to the model’s predicted values. This is exactly what we are trying to do here.  We will look at the RMSE of both the training data and testing data. What is nice about the RMSE, is that we will use this as the measure of the non-linear model as well, and in some sense be able to compare the two models that way.  RMSE is also an absolute measure of fit, since it is the square root of a variance, it can also be interpreted as the standard deviation of the unexplained variance, and has the useful property of being in the same units as the response variable. Lower values of RMSE indicate better fit. RMSE is a good measure of how accurately the model predicts the response, and it is the most important criterion for fit if the main purpose of the model is prediction, which again, is exactly what we are trying to do here.

#### Random Forest (RF) Model

For the non-linear model, we will use the random forest model.  Tony Yiu has a great blog post entitled [Understanding Random Forest: How the Algorithm Works and Why it Is So Effective](https://towardsdatascience.com/understanding-random-forest-58381e0602d2).  One benefit in this situation to use the Random Forest Model is that we can again in some sense compare to the MLR model via RMSE.  The main concept and benefit behind the RF Model in general is that there is wisdom in the group, i.e. a large number of relatively uncorrelated models (trees) operating as a committee will outperform any of the individual constituent models.  This is because the trees protect each other from their individual errors, as long as they are all not in error.  A few trees may be wrong, but many many more will be right, so the group leads the model in the correct direction.  Thus, we will use these two models for our analysis and compare the results for each day of the week.

## Goal of Project

The goal of this project is to create 2 models (one linear and one non-linear) for predicting the shares variable.  In addition to this goal, another primary goal is to use parameter functionality within R Markdown to automatically generate an analysis report for each day of the week, using each `weekday_is_` variable as a parameter.

## Reports    
    
[The Analysis for Monday is available here](MondayAnalysis.md)    
[The Analysis for Tuesday is available here](TuesdayAnalysis.md)    
[The Analysis for Wednesday is available here](WednesdayAnalysis.md)    
[The Analysis for Thursday is available here](ThursdayAnalysis.md)    
[The Analysis for Friday is available here](FridayAnalysis.md)    
[The Analysis for Saturday is available here](SaturdayAnalysis.md)    
[The Analysis for Sunday is available here](SundayAnalysis.md)    




